### ISSUE TITLE
Missing paragraph break when the play begins

### ISSUE THREAD

**Issue by juhana** [andrewschultz/the-problems-compound#79]
There should be a paragraph break here:
![missing paragraph break](https://cloud.githubusercontent.com/assets/762231/14067150/452ef73e-f466-11e5-8348-892a915c5b72.png)

**Comment by andrewschultz** [comment]
I put in a paragraph break instead of a line break. Again, I'll wait to close this til I verify it, but this looks like a quick fix. Thanks for this--line breaks are always a pain for programmer testing but others' transcripts make them so clear in a way my own transcripts don't.

Also I tidied up the text to make sure that, yes, people can be mean about looks, but they can be even worse.
